### ISSUE TITLE
Image not showing in cover

### ISSUE THREAD

**Issue by merilturock** [hypeJunction/hypeIcons#1]
When i upload the cover image the image gets uploaded but the cover image is not getting displayed i added an cover image for Page & Groups both did not display the image uploaded for cover but i am able to see the uploaded image in the crop section but i am not able to crop them as the rectangle do not apear to crop the image.

Elgg 2.2.4 

Thank you
Meril

**Comment by hypeJunction** [comment]
Covers will not magically appear on the page, you have to modify your theme to include them.
